### ISSUE TITLE
question about MANGO att_pretrain speed.

### ISSUE THREAD

**Issue by jeong-tae** [hikopensource/DAVAR-Lab-OCR#103]
Hi, I am trying to train the MANGO model from the att_pretrain, which includes character-level annotation.
However, as far as I check, it takes a long time for an epoch.
Most of the time was spent on making a character-level annotation, which was used in the CMA module.

Is it normal? or is there a bug?
I slightly change the code to expand the output of the segmentation(for example, not only centerline map, but also orientation or depth)

For your case, how much time did it take for att_pretrain?

**Comment by qiaoliang6** [comment]
Yes, the pretrain-stage is somehow time-cosuming since it involves the character-level calculation. The pretrain process on SynthText 800K cost about 3 days using 8 x Tesla V100 GPUs.   If you have a more efficient way to implement it, please bring it up.  Nevertheless, this pre-training process is a one-time thing, you can directly use the pre-training model provided by us for subsequent experiments
