### ISSUE TITLE
Question about difference between local pyramid mask and global pyramid mask

### ISSUE THREAD

**Issue by ZHEGG** [hikopensource/DAVAR-Lab-OCR#107]
Thank you for the nice code! and I have some questions about the code

![image](https://user-images.githubusercontent.com/65839993/183853266-f7293780-fd42-4a14-9c54-9d94ce6efa69.png)
![image](https://user-images.githubusercontent.com/65839993/183853376-779408f1-d516-4321-b462-808b7cb69459.png)
It looks like the c++ algorithm for global mask generation is the same as the algorithm for local mask generation in ROI in python, So I have some questions about the difference between local pyramid mask and global pyramid mask. I visualize them and find them almost same.
local mask
![PMC3681678_010_00_local_mask](https://user-images.githubusercontent.com/65839993/183855467-23f9c65e-ec06-4db7-ad0f-a63b096ac22a.png)
global mask and img
![PMC3681678_010_00_GPMA](https://user-images.githubusercontent.com/65839993/183855577-58a3f907-d00a-47bc-8b2d-ab8559d4f978.png)

Looking forward to your reply!

**Comment by qiaoliang6** [comment]
Yes, the idea is essentially the same. It is just because that in the Global Mask, we need to do mask generation for each target. At that time, we didn't find a very efficient implementation using Python to achieve parrallel computing. So it would have been slower to execute with Python. Therefore, referring to the C++ implementation of our previous text detection method (Text Perceptron Det), we implemented it in C++ to improve the calculation speed. If you have a more efficient way to implement it in python, you are welcome to contribute in current repository.

**Comment by ZHEGG** [comment]
> Yes, the idea is essentially the same. It is just because that in the Global Mask, we need to do mask generation for each target. At that time, we didn't find a very efficient implementation using Python to achieve parrallel computing. So it would have been slower to execute with Python. Therefore, referring to the C++ implementation of our previous text detection method (Text Perceptron Det), we implemented it in C++ to improve the calculation speed. If you have a more efficient way to implement it in python, you are welcome to contribute in current repository.

thank you !
