### ISSUE TITLE
LPMA branch problem of LGPMA?

### ISSUE THREAD

**Issue by cv-small-snails** [hikopensource/DAVAR-Lab-OCR#62]
In LGPMA paper,  LPMA contains Text Region Mask, Horizontal Pyramid Mask, and Vertical Pyramid Mask.
But I see the code, It only use the Text Region Mask, not use the Horizontal Pyramid Mask and Vertical Pyramid Mask?
Do I understand correctly?

**Comment by qiaoliang6** [comment]
Thank you for your problem. The released code is miragrated from our internal-used framework,  so some of the implementations are not strictly equals to the original version.  

Current version of LPMA is indeed trained with all three branches, and simply inferred with only the text region mask.  This is because the post-processing of the pyramid mask is somehow time-consuming and may affect the user experience of model in practical application. We will release the version of post-processing that uses pyramid  masks as an optional mode soon.

It is because that the

**Comment by cv-small-snails** [comment]
Thank you for your reply. I will take a closer look at your code.
